algoritmo "cardapio"
// Função :
// Autor :
// Data : 29/08/2016
// Seção de Declarações 
var
ham, cheese, fritas, refri, milk, t1, t2, t3, t4, t5, totalgeral :real



inicio
// Seção de Comandos 
escreval (" Quantos hamburgueres você:?   ")
leia (ham)
t1 <- ham * 3.00


Escreval (" Quantos cheese burger você comeu:?  ")
leia (cheese)
t2<- cheese * 2.50


escreval (" Quantas fritas você comeu:?   ")
leia (fritas)
t3 <- fritas * 2.50


Escreval (" Quantos refrigerantes você tomou:?    ")
leia (refri)
t4 <- refri * 1.00


escreval (" Quantos milkshakes:?    ")
leia (milk)
t5<- milk * 3.00


totalgeral<- t1 + t2 + t3+ t4 + t5
escreval (" Total Geral:        ",totalgeral)


Fimalgoritmo

