algoritmo "distancia"
// Função :
// Autor :
// Data : 29/08/2016
// Seção de Declarações 
var
x, x2, y, y2, distancia : real

inicio
// Seção de Comandos 
escreval ("                   Digite as coodernadas:                      ")

escreva (" Digite a primeira coord:    ")
leia(x)
Escreva (" Digite a segunda cood:      ")
leia(x2)



escreva (" Digite a primeira coord:    ")
leia(y)
Escreva (" Digite a segunda cood:      ")
leia(y2)



distancia <-raizq((x2-x)^ 2 + (y2-y) ^ 2)


escreva (" A distancia é:     ", distancia)



fimalgoritmo
