algoritmo "semnome"
// Função :
// Autor :
// Data : 22/08/2016
// Seção de Declarações 

var
   n1,n2,n3,n4,soma,media : real
   

inicio
// Seção de Comandos
   escreval ("**Calculo de média e soma**")
   escreva ("Numero 1:  ")
   leia(n1)
   escreva ("Numero 2:  ")
   leia(n2)
   escreva ("Numero 3:  ")
   leia(n3)
   escreva ("Numero 4:  ")
   leia(n4)

   soma<- n1+n2+n3+n4
   media<- (n1+n2+n3+n4)/4
   
   escreval ("A media é :   ", media)
   escreva ("A soma é  :   ", soma)

fimalgoritmo

