algoritmo "menu de opções"
// Função :
// Autor :
// Data : 19/09/2016
// Seção de Declarações 
var
opc: inteiro
nome: caracter
raiz: real
inicio
escreva (" digite o nome do usuário ")
leia (nome)
escreval (" 1- quadrado de um numero ")
escreval (" 2- numero pa ou impar " )
escreval (" 3- escrever a palavra sonho ")
escreval (" 4- calcular o sal do vendedor de carros ")
escreval (" 5- sair ")
escreval (" numero da opção  ")
leia (opc)
     escolha opc
            caso 1
            escreva ("Digite um valor:    ")
            leia(raiz)
            escreva("a raiz é :  ", raizq(raiz))
     fimescolha

// Seção de Comandos 
fimalgoritmo
