algoritmo "nome mes "
// Função :
// Autor :
// Data : 12/09/2016
// Seção de Declarações 
var
mes : inteiro

inicio
escreva ("digite nome do mes")
leia(mes)
se( mes = 1) entao
escreva ("janeiro")
        senao
        se (mes = 2) entao
        escreva ("fevereiro")
                senao
                se(mes = 3 ) entao
                escreva ("março")
                        senao
                        se (mes=4)entao
                        escreva ("abril")
                                senao
                                se( mes = 5 ) entao
                                escreva ("maio")
                                        senao
                                        se ( mes = 6 ) entao
                                        escreva ("junho")
                                                senao
                                                se(mes = 7 ) entao
                                                escreva ("julho")
                                                        senao
                                                        se (mes=8) entao
                                                        escreva ("agosto")
                                                                senao
                                                                se (mes=9) entao
                                                                escreva ("setembro")
                                                                        senao
                                                                        se (mes= 10) entao
                                                                        escreva ("outubro")
                                                                                senao
                                                                                se (mes= 11) ENTAO
                                                                                escreva ("novembro")
                                                                                        senao
                                                                                        se (mes = 12 ) entao
                                                                                        escreva ("dezembro")
                                                                                                senao
                                                                                                     escreva (" invalido")
                                                                                                fimse
                                                                                        fimse
                                                                                fimse
                                                                        fimse
                                                                fimse
                                                        fimse
                                                fimse
                                        fimse
                                fimse
                        fimse
                fimse
        fimse

fimalgoritmo

