algoritmo "ordem"
// Função :
// Autor :
// Data : 12/09/2016
// Seção de Declarações 
var
n1, n2, n3 : inteiro

inicio
escreva ("Insira 1º numero")
leia(n1)
escreva ("Insira 2º mumero")
leia(n2)
escreva ("Insira 3º numero")
leia(n3)
se (n1 < n2) e (n2 < n3) entao
escreva ("a ordem é", n3, n2, n1)
        senao
        se (n1 < n2) e (n2 > n3) entao
        escreva ("a ordem é :",n2, n3, n1)
                senao
                
// Seção de Comandos 
fimalgoritmo
