algoritmo "tabuada - repita"
// Função :
// Autor :
// Data : 03/10/2016
// Seção de Declarações 
var
tab, con, total : inteiro
inicio
con <- 0
escreval ("                                  Tabuada")
escreval ("                             escolha a tabuada")
leia (                         tab)
repita
         total <- con * tab
         escreval (con  , "  x  "  , tab , "  =  "  ,total)
         con <- con + 1
ate (con > 10)
// Seção de Comandos
fimalgoritmo
