algoritmo "tabuada - para"
// Função :
// Autor :
// Data : 03/10/2016
// Seção de Declarações 
var
tab, con, total : inteiro
inicio
escreval ("                                  Tabuada")
escreval ("                             escolha a tabuada")
leia (                         tab)
para con  de 0 ate 10 faca
         total <- con * tab
         escreval (con  , "  x  "  , tab , "  =  "  ,total)
         con <- con + 1
fimpara
// Seção de Comandos
fimalgoritmo
